#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Demo.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_GC_DEMO")]
	public partial class _DBMLDataComercialDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public _DBMLDataComercialDataContext() : 
				base(global::System.Demo.DataAccess.Properties.Settings.Default.BD_GC_DEMOConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLDataComercialDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLDataComercialDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLDataComercialDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLDataComercialDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_U_TipoDeCambio")]
		public int demo_mvc_U_TipoDeCambio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codTipoCambio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> prm_FechaProceso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(13,5)")] System.Nullable<decimal> prm_CambioCompraGOB, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(13,5)")] System.Nullable<decimal> prm_CambioVentasGOB, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(13,5)")] System.Nullable<decimal> prm_CambioCompraPRL, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(13,5)")] System.Nullable<decimal> prm_CambioVentasPRL, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> prm_Estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string prm_SegUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string prm_SegMaquina)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_codTipoCambio, prm_FechaProceso, prm_CodigoArguMoneda, prm_CambioCompraGOB, prm_CambioVentasGOB, prm_CambioCompraPRL, prm_CambioVentasPRL, prm_Estado, prm_SegUsuarioEdita, prm_SegMaquina);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_D_DocumentoEstado")]
		public int demo_mvc_D_DocumentoEstado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codDocumentoEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegDocumento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codDocumentoEstado, prm_codRegDocumento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_D_TipoDeCambio")]
		public int demo_mvc_D_TipoDeCambio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codTipoCambio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_codTipoCambio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_I_DocumentoEstado")]
		public int demo_mvc_I_DocumentoEstado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> prm_codDocumentoEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> prm_indActivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string prm_segUsuarioCrea)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codDocumentoEstado, prm_codRegDocumento, prm_codRegEstado, prm_codEstado, prm_indActivo, prm_segUsuarioCrea);
			prm_codDocumentoEstado = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_I_TipoDeCambio")]
		public int demo_mvc_I_TipoDeCambio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> prm_codTipoCambio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> prm_FechaProceso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(13,5)")] System.Nullable<decimal> prm_CambioCompraGOB, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(13,5)")] System.Nullable<decimal> prm_CambioVentasGOB, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(13,5)")] System.Nullable<decimal> prm_CambioCompraPRL, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(13,5)")] System.Nullable<decimal> prm_CambioVentasPRL, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> prm_Estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string prm_SegUsuarioCrea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string prm_SegMaquina)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codTipoCambio, prm_codEmpresa, prm_FechaProceso, prm_CodigoArguMoneda, prm_CambioCompraGOB, prm_CambioVentasGOB, prm_CambioCompraPRL, prm_CambioVentasPRL, prm_Estado, prm_SegUsuarioCrea, prm_SegMaquina);
			prm_codTipoCambio = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_S_DocumentoEstado")]
		public ISingleResult<demo_mvc_S_DocumentoEstadoResult> demo_mvc_S_DocumentoEstado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codDocumentoEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegEstado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codDocumentoEstado, prm_codRegDocumento, prm_codRegEstado);
			return ((ISingleResult<demo_mvc_S_DocumentoEstadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_S_DocumentoEstado_Paged")]
		public ISingleResult<demo_mvc_S_DocumentoEstado_PagedResult> demo_mvc_S_DocumentoEstado_Paged([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_NumPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_TamPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string prm_OrdenPor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_OrdenTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codDocumentoEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegEstado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_NumPagina, prm_TamPagina, prm_OrdenPor, prm_OrdenTipo, prm_codDocumentoEstado, prm_codRegDocumento, prm_codRegEstado);
			return ((ISingleResult<demo_mvc_S_DocumentoEstado_PagedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_S_TipoDeCambio")]
		public ISingleResult<demo_mvc_S_TipoDeCambioResult> demo_mvc_S_TipoDeCambio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codTipoCambio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaProcesoINI, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaProcesoFIN, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> prm_Estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_codTipoCambio, prm_FechaProcesoINI, prm_FechaProcesoFIN, prm_CodigoArguMoneda, prm_Estado);
			return ((ISingleResult<demo_mvc_S_TipoDeCambioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_U_DocumentoEstado")]
		public int demo_mvc_U_DocumentoEstado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codDocumentoEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> prm_indActivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string prm_segUsuarioEdita)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codDocumentoEstado, prm_codRegDocumento, prm_codRegEstado, prm_codEstado, prm_indActivo, prm_segUsuarioEdita);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_S_TipoDeCambio_Paged")]
		public ISingleResult<demo_mvc_S_TipoDeCambio_PagedResult> demo_mvc_S_TipoDeCambio_Paged([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_NumPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_TamPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string prm_OrdenPor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_OrdenTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaProcesoINI, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaProcesoFIN, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> prm_Estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_NumPagina, prm_TamPagina, prm_OrdenPor, prm_OrdenTipo, prm_codEmpresa, prm_FechaProcesoINI, prm_FechaProcesoFIN, prm_CodigoArguMoneda, prm_Estado);
			return ((ISingleResult<demo_mvc_S_TipoDeCambio_PagedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.demo_mvc_S_TipoDeCambio_Ultimo")]
		public ISingleResult<demo_mvc_S_TipoDeCambio_UltimoResult> demo_mvc_S_TipoDeCambio_Ultimo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> prm_Estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_CodigoArguMoneda, prm_Estado);
			return ((ISingleResult<demo_mvc_S_TipoDeCambio_UltimoResult>)(result.ReturnValue));
		}
	}
	
	public partial class demo_mvc_S_DocumentoEstadoResult
	{
		
		private int _codDocumentoEstado;
		
		private string _codRegDocumento;
		
		private string _codRegDocumentoNombre;
		
		private string _codRegEstado;
		
		private string _codRegEstadoNombre;
		
		private System.Nullable<int> _codEstado;
		
		private bool _indActivo;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.DateTime _segFechaEdita;
		
		private string _segMaquinaEdita;
		
		public demo_mvc_S_DocumentoEstadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumentoEstado", DbType="Int NOT NULL")]
		public int codDocumentoEstado
		{
			get
			{
				return this._codDocumentoEstado;
			}
			set
			{
				if ((this._codDocumentoEstado != value))
				{
					this._codDocumentoEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegDocumento", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegDocumento
		{
			get
			{
				return this._codRegDocumento;
			}
			set
			{
				if ((this._codRegDocumento != value))
				{
					this._codRegDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegDocumentoNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string codRegDocumentoNombre
		{
			get
			{
				return this._codRegDocumentoNombre;
			}
			set
			{
				if ((this._codRegDocumentoNombre != value))
				{
					this._codRegDocumentoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstado", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegEstado
		{
			get
			{
				return this._codRegEstado;
			}
			set
			{
				if ((this._codRegEstado != value))
				{
					this._codRegEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstadoNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string codRegEstadoNombre
		{
			get
			{
				return this._codRegEstadoNombre;
			}
			set
			{
				if ((this._codRegEstadoNombre != value))
				{
					this._codRegEstadoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEstado", DbType="Int")]
		public System.Nullable<int> codEstado
		{
			get
			{
				return this._codEstado;
			}
			set
			{
				if ((this._codEstado != value))
				{
					this._codEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indActivo", DbType="Bit NOT NULL")]
		public bool indActivo
		{
			get
			{
				return this._indActivo;
			}
			set
			{
				if ((this._indActivo != value))
				{
					this._indActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaEdita", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segMaquinaEdita
		{
			get
			{
				return this._segMaquinaEdita;
			}
			set
			{
				if ((this._segMaquinaEdita != value))
				{
					this._segMaquinaEdita = value;
				}
			}
		}
	}
	
	public partial class demo_mvc_S_DocumentoEstado_PagedResult
	{
		
		private System.Nullable<int> _TOTALROWS;
		
		private System.Nullable<long> _ROWNUM;
		
		private int _codDocumentoEstado;
		
		private string _codRegDocumento;
		
		private string _codRegDocumentoNombre;
		
		private string _codRegEstado;
		
		private string _codRegEstadoNombre;
		
		private string _codRegEstadoColor;
		
		private System.Nullable<int> _codEstado;
		
		private bool _indActivo;
		
		private string _segUsuarioCrea;
		
		private System.DateTime _segFechaCrea;
		
		private string _segUsuarioEdita;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquina;
		
		public demo_mvc_S_DocumentoEstado_PagedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALROWS", DbType="Int")]
		public System.Nullable<int> TOTALROWS
		{
			get
			{
				return this._TOTALROWS;
			}
			set
			{
				if ((this._TOTALROWS != value))
				{
					this._TOTALROWS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWNUM", DbType="BigInt")]
		public System.Nullable<long> ROWNUM
		{
			get
			{
				return this._ROWNUM;
			}
			set
			{
				if ((this._ROWNUM != value))
				{
					this._ROWNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumentoEstado", DbType="Int NOT NULL")]
		public int codDocumentoEstado
		{
			get
			{
				return this._codDocumentoEstado;
			}
			set
			{
				if ((this._codDocumentoEstado != value))
				{
					this._codDocumentoEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegDocumento", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegDocumento
		{
			get
			{
				return this._codRegDocumento;
			}
			set
			{
				if ((this._codRegDocumento != value))
				{
					this._codRegDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegDocumentoNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string codRegDocumentoNombre
		{
			get
			{
				return this._codRegDocumentoNombre;
			}
			set
			{
				if ((this._codRegDocumentoNombre != value))
				{
					this._codRegDocumentoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstado", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegEstado
		{
			get
			{
				return this._codRegEstado;
			}
			set
			{
				if ((this._codRegEstado != value))
				{
					this._codRegEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstadoNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string codRegEstadoNombre
		{
			get
			{
				return this._codRegEstadoNombre;
			}
			set
			{
				if ((this._codRegEstadoNombre != value))
				{
					this._codRegEstadoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstadoColor", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string codRegEstadoColor
		{
			get
			{
				return this._codRegEstadoColor;
			}
			set
			{
				if ((this._codRegEstadoColor != value))
				{
					this._codRegEstadoColor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEstado", DbType="Int")]
		public System.Nullable<int> codEstado
		{
			get
			{
				return this._codEstado;
			}
			set
			{
				if ((this._codEstado != value))
				{
					this._codEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indActivo", DbType="Bit NOT NULL")]
		public bool indActivo
		{
			get
			{
				return this._indActivo;
			}
			set
			{
				if ((this._indActivo != value))
				{
					this._indActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(50)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquina", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segMaquina
		{
			get
			{
				return this._segMaquina;
			}
			set
			{
				if ((this._segMaquina != value))
				{
					this._segMaquina = value;
				}
			}
		}
	}
	
	public partial class demo_mvc_S_TipoDeCambioResult
	{
		
		private int _codTipoCambio;
		
		private System.DateTime _FechaProceso;
		
		private string _CodigoArguMoneda;
		
		private string _CodigoArguMonedaNombre;
		
		private decimal _CambioCompraGOB;
		
		private decimal _CambioVentasGOB;
		
		private decimal _CambioCompraPRL;
		
		private decimal _CambioVentasPRL;
		
		private bool _Estado;
		
		private string _SegUsuarioCrea;
		
		private string _SegUsuarioEdita;
		
		private System.DateTime _SegFechaCrea;
		
		private System.Nullable<System.DateTime> _SegFechaEdita;
		
		private string _SegMaquina;
		
		public demo_mvc_S_TipoDeCambioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoCambio", DbType="Int NOT NULL")]
		public int codTipoCambio
		{
			get
			{
				return this._codTipoCambio;
			}
			set
			{
				if ((this._codTipoCambio != value))
				{
					this._codTipoCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaProceso", DbType="Date NOT NULL")]
		public System.DateTime FechaProceso
		{
			get
			{
				return this._FechaProceso;
			}
			set
			{
				if ((this._FechaProceso != value))
				{
					this._FechaProceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMonedaNombre", DbType="VarChar(100)")]
		public string CodigoArguMonedaNombre
		{
			get
			{
				return this._CodigoArguMonedaNombre;
			}
			set
			{
				if ((this._CodigoArguMonedaNombre != value))
				{
					this._CodigoArguMonedaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioCompraGOB", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioCompraGOB
		{
			get
			{
				return this._CambioCompraGOB;
			}
			set
			{
				if ((this._CambioCompraGOB != value))
				{
					this._CambioCompraGOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioVentasGOB", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioVentasGOB
		{
			get
			{
				return this._CambioVentasGOB;
			}
			set
			{
				if ((this._CambioVentasGOB != value))
				{
					this._CambioVentasGOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioCompraPRL", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioCompraPRL
		{
			get
			{
				return this._CambioCompraPRL;
			}
			set
			{
				if ((this._CambioCompraPRL != value))
				{
					this._CambioCompraPRL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioVentasPRL", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioVentasPRL
		{
			get
			{
				return this._CambioVentasPRL;
			}
			set
			{
				if ((this._CambioVentasPRL != value))
				{
					this._CambioVentasPRL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioCrea", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegUsuarioCrea
		{
			get
			{
				return this._SegUsuarioCrea;
			}
			set
			{
				if ((this._SegUsuarioCrea != value))
				{
					this._SegUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioEdita", DbType="VarChar(50)")]
		public string SegUsuarioEdita
		{
			get
			{
				return this._SegUsuarioEdita;
			}
			set
			{
				if ((this._SegUsuarioEdita != value))
				{
					this._SegUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaCrea
		{
			get
			{
				return this._SegFechaCrea;
			}
			set
			{
				if ((this._SegFechaCrea != value))
				{
					this._SegFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaEdita
		{
			get
			{
				return this._SegFechaEdita;
			}
			set
			{
				if ((this._SegFechaEdita != value))
				{
					this._SegFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegMaquina", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
	}
	
	public partial class demo_mvc_S_TipoDeCambio_PagedResult
	{
		
		private int _codTipoCambio;
		
		private System.DateTime _FechaProceso;
		
		private string _CodigoArguMoneda;
		
		private string _CodigoArguMonedaNombre;
		
		private decimal _CambioCompraGOB;
		
		private decimal _CambioVentasGOB;
		
		private decimal _CambioCompraPRL;
		
		private decimal _CambioVentasPRL;
		
		private bool _Estado;
		
		private string _SegUsuarioCrea;
		
		private string _SegUsuarioEdita;
		
		private System.DateTime _SegFechaCrea;
		
		private System.Nullable<System.DateTime> _SegFechaEdita;
		
		private string _SegMaquina;
		
		private System.Nullable<int> _TOTALROWS;
		
		private System.Nullable<long> _ROWNUM;
		
		public demo_mvc_S_TipoDeCambio_PagedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoCambio", DbType="Int NOT NULL")]
		public int codTipoCambio
		{
			get
			{
				return this._codTipoCambio;
			}
			set
			{
				if ((this._codTipoCambio != value))
				{
					this._codTipoCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaProceso", DbType="Date NOT NULL")]
		public System.DateTime FechaProceso
		{
			get
			{
				return this._FechaProceso;
			}
			set
			{
				if ((this._FechaProceso != value))
				{
					this._FechaProceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMonedaNombre", DbType="VarChar(100)")]
		public string CodigoArguMonedaNombre
		{
			get
			{
				return this._CodigoArguMonedaNombre;
			}
			set
			{
				if ((this._CodigoArguMonedaNombre != value))
				{
					this._CodigoArguMonedaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioCompraGOB", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioCompraGOB
		{
			get
			{
				return this._CambioCompraGOB;
			}
			set
			{
				if ((this._CambioCompraGOB != value))
				{
					this._CambioCompraGOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioVentasGOB", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioVentasGOB
		{
			get
			{
				return this._CambioVentasGOB;
			}
			set
			{
				if ((this._CambioVentasGOB != value))
				{
					this._CambioVentasGOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioCompraPRL", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioCompraPRL
		{
			get
			{
				return this._CambioCompraPRL;
			}
			set
			{
				if ((this._CambioCompraPRL != value))
				{
					this._CambioCompraPRL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioVentasPRL", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioVentasPRL
		{
			get
			{
				return this._CambioVentasPRL;
			}
			set
			{
				if ((this._CambioVentasPRL != value))
				{
					this._CambioVentasPRL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioCrea", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegUsuarioCrea
		{
			get
			{
				return this._SegUsuarioCrea;
			}
			set
			{
				if ((this._SegUsuarioCrea != value))
				{
					this._SegUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioEdita", DbType="VarChar(50)")]
		public string SegUsuarioEdita
		{
			get
			{
				return this._SegUsuarioEdita;
			}
			set
			{
				if ((this._SegUsuarioEdita != value))
				{
					this._SegUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaCrea
		{
			get
			{
				return this._SegFechaCrea;
			}
			set
			{
				if ((this._SegFechaCrea != value))
				{
					this._SegFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaEdita
		{
			get
			{
				return this._SegFechaEdita;
			}
			set
			{
				if ((this._SegFechaEdita != value))
				{
					this._SegFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegMaquina", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALROWS", DbType="Int")]
		public System.Nullable<int> TOTALROWS
		{
			get
			{
				return this._TOTALROWS;
			}
			set
			{
				if ((this._TOTALROWS != value))
				{
					this._TOTALROWS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWNUM", DbType="BigInt")]
		public System.Nullable<long> ROWNUM
		{
			get
			{
				return this._ROWNUM;
			}
			set
			{
				if ((this._ROWNUM != value))
				{
					this._ROWNUM = value;
				}
			}
		}
	}
	
	public partial class demo_mvc_S_TipoDeCambio_UltimoResult
	{
		
		private int _codTipoCambio;
		
		private System.DateTime _FechaProceso;
		
		private string _CodigoArguMoneda;
		
		private string _CodigoArguMonedaNombre;
		
		private decimal _CambioCompraGOB;
		
		private decimal _CambioVentasGOB;
		
		private decimal _CambioCompraPRL;
		
		private decimal _CambioVentasPRL;
		
		private bool _Estado;
		
		private string _SegUsuarioCrea;
		
		private string _SegUsuarioEdita;
		
		private System.DateTime _SegFechaCrea;
		
		private System.Nullable<System.DateTime> _SegFechaEdita;
		
		private string _SegMaquina;
		
		public demo_mvc_S_TipoDeCambio_UltimoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoCambio", DbType="Int NOT NULL")]
		public int codTipoCambio
		{
			get
			{
				return this._codTipoCambio;
			}
			set
			{
				if ((this._codTipoCambio != value))
				{
					this._codTipoCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaProceso", DbType="Date NOT NULL")]
		public System.DateTime FechaProceso
		{
			get
			{
				return this._FechaProceso;
			}
			set
			{
				if ((this._FechaProceso != value))
				{
					this._FechaProceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMonedaNombre", DbType="VarChar(100)")]
		public string CodigoArguMonedaNombre
		{
			get
			{
				return this._CodigoArguMonedaNombre;
			}
			set
			{
				if ((this._CodigoArguMonedaNombre != value))
				{
					this._CodigoArguMonedaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioCompraGOB", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioCompraGOB
		{
			get
			{
				return this._CambioCompraGOB;
			}
			set
			{
				if ((this._CambioCompraGOB != value))
				{
					this._CambioCompraGOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioVentasGOB", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioVentasGOB
		{
			get
			{
				return this._CambioVentasGOB;
			}
			set
			{
				if ((this._CambioVentasGOB != value))
				{
					this._CambioVentasGOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioCompraPRL", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioCompraPRL
		{
			get
			{
				return this._CambioCompraPRL;
			}
			set
			{
				if ((this._CambioCompraPRL != value))
				{
					this._CambioCompraPRL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CambioVentasPRL", DbType="Decimal(6,4) NOT NULL")]
		public decimal CambioVentasPRL
		{
			get
			{
				return this._CambioVentasPRL;
			}
			set
			{
				if ((this._CambioVentasPRL != value))
				{
					this._CambioVentasPRL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit NOT NULL")]
		public bool Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioCrea", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SegUsuarioCrea
		{
			get
			{
				return this._SegUsuarioCrea;
			}
			set
			{
				if ((this._SegUsuarioCrea != value))
				{
					this._SegUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioEdita", DbType="VarChar(50)")]
		public string SegUsuarioEdita
		{
			get
			{
				return this._SegUsuarioEdita;
			}
			set
			{
				if ((this._SegUsuarioEdita != value))
				{
					this._SegUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaCrea
		{
			get
			{
				return this._SegFechaCrea;
			}
			set
			{
				if ((this._SegFechaCrea != value))
				{
					this._SegFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaEdita
		{
			get
			{
				return this._SegFechaEdita;
			}
			set
			{
				if ((this._SegFechaEdita != value))
				{
					this._SegFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegMaquina", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
