<?xml version="1.0" encoding="utf-8"?><Database Name="BD_GC_DEMO" Class="_DBMLDataMaestrosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAP01-OCARRIL\SQLEXPRESSCROM;Initial Catalog=BD_GC_DEMO;User ID=sa" SettingsObjectName="System.Demo.DataAccess.Properties.Settings" SettingsPropertyName="BD_GC_DEMOConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="Maestros.demo_mvc_D_Configuracion" Method="demo_mvc_D_Configuracion">
    <Parameter Name="prm_codEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_codConfiguracion" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_segUsuarioEdita" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.demo_mvc_I_Configuracion" Method="demo_mvc_I_Configuracion">
    <Parameter Name="prm_codConfiguracion" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="prm_codEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_codKeyConfig" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_codTabla" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="prm_numNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_indOrden" Type="System.String" DbType="Char(4)" />
    <Parameter Name="prm_indTipoValor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="prm_desValor" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="prm_gloDescripcion" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="prm_indGenerico" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_desGrupo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_segUsuarioCrea" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_segMaquina" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.demo_mvc_S_Configuracion" Method="demo_mvc_S_Configuracion">
    <Parameter Name="prm_codEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_codConfiguracion" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_codKeyConfig" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="demo_mvc_S_ConfiguracionResult">
      <Column Name="codConfiguracion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codKeyConfig" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="codTabla" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="numNivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="indOrden" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="indTipoValor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="desValor" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="indGenerico" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="desGrupo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="indActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquina" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Maestros.demo_mvc_S_Configuracion_Paged" Method="demo_mvc_S_Configuracion_Paged">
    <Parameter Name="prm_NumPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_TamPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_OrdenPor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_OrdenTipo" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="prm_codEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_codKeyConfig" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_codTabla" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="prm_desValor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="demo_mvc_S_Configuracion_PagedResult">
      <Column Name="codConfiguracion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codKeyConfig" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="codTabla" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="numNivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="indOrden" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="indTipoValor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="desValor" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="indGenerico" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="desGrupo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="indActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquina" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TOTALROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWNUM" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Maestros.demo_mvc_U_Configuracion" Method="demo_mvc_U_Configuracion">
    <Parameter Name="prm_codEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_codConfiguracion" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_codKeyConfig" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_codTabla" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="prm_numNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_indOrden" Type="System.String" DbType="Char(4)" />
    <Parameter Name="prm_indTipoValor" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="prm_desValor" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="prm_gloDescripcion" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="prm_indGenerico" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_desGrupo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_segUsuarioEdita" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.demo_mvc_U_ConfiguracionConfig" Method="demo_mvc_U_ConfiguracionConfig">
    <Parameter Name="prm_codEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_codKeyConfig" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_desValor" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="prm_segUsuarioEdita" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_segMaquina" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.demo_mvc_S_Tabla" Method="demo_mvc_S_Tabla">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="demo_mvc_S_TablaResult">
      <Column Name="codTabla" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="numLongitudNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="indNivel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TipoArgumento" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="TipoGeneracion" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="indActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="segUsuCrea" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuEdita" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Maestros.demo_mvc_S_Registro_Combo" Method="demo_mvc_S_Registro_Combo">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="Char(5)" />
    <Parameter Name="prm_codRegistro" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_numNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="demo_mvc_S_Registro_ComboResult">
      <Column Name="codTabla" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="codRegistro" Type="System.String" DbType="VarChar(17) NOT NULL" CanBeNull="false" />
      <Column Name="numNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="desValorDecimal" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="desValorCadena" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="desValorLogico" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="desValorEntero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="desValorFecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="indActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="codValorSunat" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="codigoTMP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="numLongitudNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segMaquinaEdita" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>