//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CROM.GC.Controllers.wcfSeguridad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/CROM.Seguridad.BussinesEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CROM.GC.Controllers.wcfSeguridad.UsuarioAux))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clvPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codArguPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desNombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desPreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indAccesoGerencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indCambiaCodPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indCambiaDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indCambioPrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indJefeCajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indRestricPorPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indUsuarioSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indVendedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime segFechaHoraCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> segFechaHoraEditaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segMaquinaOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segUsuarioCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segUsuarioEditaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clvPassword {
            get {
                return this.clvPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.clvPasswordField, value) != true)) {
                    this.clvPasswordField = value;
                    this.RaisePropertyChanged("clvPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codArguPais {
            get {
                return this.codArguPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.codArguPaisField, value) != true)) {
                    this.codArguPaisField = value;
                    this.RaisePropertyChanged("codArguPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEmpleado {
            get {
                return this.codEmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.codEmpleadoField, value) != true)) {
                    this.codEmpleadoField = value;
                    this.RaisePropertyChanged("codEmpleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codUsuario {
            get {
                return this.codUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.codUsuarioField, value) != true)) {
                    this.codUsuarioField = value;
                    this.RaisePropertyChanged("codUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desApellidos {
            get {
                return this.desApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.desApellidosField, value) != true)) {
                    this.desApellidosField = value;
                    this.RaisePropertyChanged("desApellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desCorreo {
            get {
                return this.desCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.desCorreoField, value) != true)) {
                    this.desCorreoField = value;
                    this.RaisePropertyChanged("desCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desLogin {
            get {
                return this.desLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.desLoginField, value) != true)) {
                    this.desLoginField = value;
                    this.RaisePropertyChanged("desLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desNombres {
            get {
                return this.desNombresField;
            }
            set {
                if ((object.ReferenceEquals(this.desNombresField, value) != true)) {
                    this.desNombresField = value;
                    this.RaisePropertyChanged("desNombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desPregunta {
            get {
                return this.desPreguntaField;
            }
            set {
                if ((object.ReferenceEquals(this.desPreguntaField, value) != true)) {
                    this.desPreguntaField = value;
                    this.RaisePropertyChanged("desPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desRespuesta {
            get {
                return this.desRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.desRespuestaField, value) != true)) {
                    this.desRespuestaField = value;
                    this.RaisePropertyChanged("desRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desTelefono {
            get {
                return this.desTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.desTelefonoField, value) != true)) {
                    this.desTelefonoField = value;
                    this.RaisePropertyChanged("desTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indAccesoGerencial {
            get {
                return this.indAccesoGerencialField;
            }
            set {
                if ((this.indAccesoGerencialField.Equals(value) != true)) {
                    this.indAccesoGerencialField = value;
                    this.RaisePropertyChanged("indAccesoGerencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indCambiaCodPersona {
            get {
                return this.indCambiaCodPersonaField;
            }
            set {
                if ((this.indCambiaCodPersonaField.Equals(value) != true)) {
                    this.indCambiaCodPersonaField = value;
                    this.RaisePropertyChanged("indCambiaCodPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indCambiaDescuento {
            get {
                return this.indCambiaDescuentoField;
            }
            set {
                if ((this.indCambiaDescuentoField.Equals(value) != true)) {
                    this.indCambiaDescuentoField = value;
                    this.RaisePropertyChanged("indCambiaDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indCambioPrecio {
            get {
                return this.indCambioPrecioField;
            }
            set {
                if ((this.indCambioPrecioField.Equals(value) != true)) {
                    this.indCambioPrecioField = value;
                    this.RaisePropertyChanged("indCambioPrecio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indEstado {
            get {
                return this.indEstadoField;
            }
            set {
                if ((this.indEstadoField.Equals(value) != true)) {
                    this.indEstadoField = value;
                    this.RaisePropertyChanged("indEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indJefeCaja {
            get {
                return this.indJefeCajaField;
            }
            set {
                if ((this.indJefeCajaField.Equals(value) != true)) {
                    this.indJefeCajaField = value;
                    this.RaisePropertyChanged("indJefeCaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indRestricPorPais {
            get {
                return this.indRestricPorPaisField;
            }
            set {
                if ((this.indRestricPorPaisField.Equals(value) != true)) {
                    this.indRestricPorPaisField = value;
                    this.RaisePropertyChanged("indRestricPorPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indUsuarioSistema {
            get {
                return this.indUsuarioSistemaField;
            }
            set {
                if ((this.indUsuarioSistemaField.Equals(value) != true)) {
                    this.indUsuarioSistemaField = value;
                    this.RaisePropertyChanged("indUsuarioSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indVendedor {
            get {
                return this.indVendedorField;
            }
            set {
                if ((this.indVendedorField.Equals(value) != true)) {
                    this.indVendedorField = value;
                    this.RaisePropertyChanged("indVendedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime segFechaHoraCrea {
            get {
                return this.segFechaHoraCreaField;
            }
            set {
                if ((this.segFechaHoraCreaField.Equals(value) != true)) {
                    this.segFechaHoraCreaField = value;
                    this.RaisePropertyChanged("segFechaHoraCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> segFechaHoraEdita {
            get {
                return this.segFechaHoraEditaField;
            }
            set {
                if ((this.segFechaHoraEditaField.Equals(value) != true)) {
                    this.segFechaHoraEditaField = value;
                    this.RaisePropertyChanged("segFechaHoraEdita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segMaquinaOrigen {
            get {
                return this.segMaquinaOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.segMaquinaOrigenField, value) != true)) {
                    this.segMaquinaOrigenField = value;
                    this.RaisePropertyChanged("segMaquinaOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segUsuarioCrea {
            get {
                return this.segUsuarioCreaField;
            }
            set {
                if ((object.ReferenceEquals(this.segUsuarioCreaField, value) != true)) {
                    this.segUsuarioCreaField = value;
                    this.RaisePropertyChanged("segUsuarioCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segUsuarioEdita {
            get {
                return this.segUsuarioEditaField;
            }
            set {
                if ((object.ReferenceEquals(this.segUsuarioEditaField, value) != true)) {
                    this.segUsuarioEditaField = value;
                    this.RaisePropertyChanged("segUsuarioEdita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioAux", Namespace="http://schemas.datacontract.org/2004/07/CROM.Seguridad.BussinesEntities")]
    [System.SerializableAttribute()]
    public partial class UsuarioAux : CROM.GC.Controllers.wcfSeguridad.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPersonaEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPersonaEmpresaDomicilioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPersonaEmpresaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPersonaRUCEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPuntoVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPuntoVentaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codRolNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codrguPaisNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desApellidosNombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CROM.GC.Controllers.wcfSeguridad.RolOpcionAux[] listaRolOpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CROM.GC.Controllers.wcfSeguridad.UsuarioIngresoAux[] listaUsuarioIngresoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPersonaEmpresa {
            get {
                return this.codPersonaEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.codPersonaEmpresaField, value) != true)) {
                    this.codPersonaEmpresaField = value;
                    this.RaisePropertyChanged("codPersonaEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPersonaEmpresaDomicilio {
            get {
                return this.codPersonaEmpresaDomicilioField;
            }
            set {
                if ((object.ReferenceEquals(this.codPersonaEmpresaDomicilioField, value) != true)) {
                    this.codPersonaEmpresaDomicilioField = value;
                    this.RaisePropertyChanged("codPersonaEmpresaDomicilio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPersonaEmpresaNombre {
            get {
                return this.codPersonaEmpresaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codPersonaEmpresaNombreField, value) != true)) {
                    this.codPersonaEmpresaNombreField = value;
                    this.RaisePropertyChanged("codPersonaEmpresaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPersonaRUCEmpresa {
            get {
                return this.codPersonaRUCEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.codPersonaRUCEmpresaField, value) != true)) {
                    this.codPersonaRUCEmpresaField = value;
                    this.RaisePropertyChanged("codPersonaRUCEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPuntoVenta {
            get {
                return this.codPuntoVentaField;
            }
            set {
                if ((object.ReferenceEquals(this.codPuntoVentaField, value) != true)) {
                    this.codPuntoVentaField = value;
                    this.RaisePropertyChanged("codPuntoVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPuntoVentaNombre {
            get {
                return this.codPuntoVentaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codPuntoVentaNombreField, value) != true)) {
                    this.codPuntoVentaNombreField = value;
                    this.RaisePropertyChanged("codPuntoVentaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codRol {
            get {
                return this.codRolField;
            }
            set {
                if ((object.ReferenceEquals(this.codRolField, value) != true)) {
                    this.codRolField = value;
                    this.RaisePropertyChanged("codRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codRolNombre {
            get {
                return this.codRolNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codRolNombreField, value) != true)) {
                    this.codRolNombreField = value;
                    this.RaisePropertyChanged("codRolNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codrguPaisNombre {
            get {
                return this.codrguPaisNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codrguPaisNombreField, value) != true)) {
                    this.codrguPaisNombreField = value;
                    this.RaisePropertyChanged("codrguPaisNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desApellidosNombres {
            get {
                return this.desApellidosNombresField;
            }
            set {
                if ((object.ReferenceEquals(this.desApellidosNombresField, value) != true)) {
                    this.desApellidosNombresField = value;
                    this.RaisePropertyChanged("desApellidosNombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CROM.GC.Controllers.wcfSeguridad.RolOpcionAux[] listaRolOpcion {
            get {
                return this.listaRolOpcionField;
            }
            set {
                if ((object.ReferenceEquals(this.listaRolOpcionField, value) != true)) {
                    this.listaRolOpcionField = value;
                    this.RaisePropertyChanged("listaRolOpcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CROM.GC.Controllers.wcfSeguridad.UsuarioIngresoAux[] listaUsuarioIngreso {
            get {
                return this.listaUsuarioIngresoField;
            }
            set {
                if ((object.ReferenceEquals(this.listaUsuarioIngresoField, value) != true)) {
                    this.listaUsuarioIngresoField = value;
                    this.RaisePropertyChanged("listaUsuarioIngreso");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolOpcionAux", Namespace="http://schemas.datacontract.org/2004/07/CROM.Seguridad.BussinesEntities")]
    [System.SerializableAttribute()]
    public partial class RolOpcionAux : CROM.GC.Controllers.wcfSeguridad.RolOpcion {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codOpcionDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codOpcionEnlaceURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codOpcionEnlaceWINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codOpcionNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codOpcionPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codRolNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indAsignarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codOpcionDescripcion {
            get {
                return this.codOpcionDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.codOpcionDescripcionField, value) != true)) {
                    this.codOpcionDescripcionField = value;
                    this.RaisePropertyChanged("codOpcionDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codOpcionEnlaceURL {
            get {
                return this.codOpcionEnlaceURLField;
            }
            set {
                if ((object.ReferenceEquals(this.codOpcionEnlaceURLField, value) != true)) {
                    this.codOpcionEnlaceURLField = value;
                    this.RaisePropertyChanged("codOpcionEnlaceURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codOpcionEnlaceWIN {
            get {
                return this.codOpcionEnlaceWINField;
            }
            set {
                if ((object.ReferenceEquals(this.codOpcionEnlaceWINField, value) != true)) {
                    this.codOpcionEnlaceWINField = value;
                    this.RaisePropertyChanged("codOpcionEnlaceWIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codOpcionNombre {
            get {
                return this.codOpcionNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codOpcionNombreField, value) != true)) {
                    this.codOpcionNombreField = value;
                    this.RaisePropertyChanged("codOpcionNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codOpcionPadre {
            get {
                return this.codOpcionPadreField;
            }
            set {
                if ((object.ReferenceEquals(this.codOpcionPadreField, value) != true)) {
                    this.codOpcionPadreField = value;
                    this.RaisePropertyChanged("codOpcionPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codRolNombre {
            get {
                return this.codRolNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codRolNombreField, value) != true)) {
                    this.codRolNombreField = value;
                    this.RaisePropertyChanged("codRolNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indAsignar {
            get {
                return this.indAsignarField;
            }
            set {
                if ((this.indAsignarField.Equals(value) != true)) {
                    this.indAsignarField = value;
                    this.RaisePropertyChanged("indAsignar");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioIngresoAux", Namespace="http://schemas.datacontract.org/2004/07/CROM.Seguridad.BussinesEntities")]
    [System.SerializableAttribute()]
    public partial class UsuarioIngresoAux : CROM.GC.Controllers.wcfSeguridad.UsuarioIngreso {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codRolNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codSistemaNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codUsuarioNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desLoginActualField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codRolNombre {
            get {
                return this.codRolNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codRolNombreField, value) != true)) {
                    this.codRolNombreField = value;
                    this.RaisePropertyChanged("codRolNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codSistemaNombre {
            get {
                return this.codSistemaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codSistemaNombreField, value) != true)) {
                    this.codSistemaNombreField = value;
                    this.RaisePropertyChanged("codSistemaNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codUsuarioNombre {
            get {
                return this.codUsuarioNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codUsuarioNombreField, value) != true)) {
                    this.codUsuarioNombreField = value;
                    this.RaisePropertyChanged("codUsuarioNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desLoginActual {
            get {
                return this.desLoginActualField;
            }
            set {
                if ((object.ReferenceEquals(this.desLoginActualField, value) != true)) {
                    this.desLoginActualField = value;
                    this.RaisePropertyChanged("desLoginActual");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolOpcion", Namespace="http://schemas.datacontract.org/2004/07/CROM.Seguridad.BussinesEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CROM.GC.Controllers.wcfSeguridad.RolOpcionAux))]
    public partial class RolOpcion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codOpcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indEditarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indEliminarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indExportaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indImportaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indImprimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indNuevoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indOtroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indVerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime segFechaHoraCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> segFechaHoraEditaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segMaquinaOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segUsuarioCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segUsuarioEditaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codOpcion {
            get {
                return this.codOpcionField;
            }
            set {
                if ((object.ReferenceEquals(this.codOpcionField, value) != true)) {
                    this.codOpcionField = value;
                    this.RaisePropertyChanged("codOpcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codRol {
            get {
                return this.codRolField;
            }
            set {
                if ((object.ReferenceEquals(this.codRolField, value) != true)) {
                    this.codRolField = value;
                    this.RaisePropertyChanged("codRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indEditar {
            get {
                return this.indEditarField;
            }
            set {
                if ((this.indEditarField.Equals(value) != true)) {
                    this.indEditarField = value;
                    this.RaisePropertyChanged("indEditar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indEliminar {
            get {
                return this.indEliminarField;
            }
            set {
                if ((this.indEliminarField.Equals(value) != true)) {
                    this.indEliminarField = value;
                    this.RaisePropertyChanged("indEliminar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indExporta {
            get {
                return this.indExportaField;
            }
            set {
                if ((this.indExportaField.Equals(value) != true)) {
                    this.indExportaField = value;
                    this.RaisePropertyChanged("indExporta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indImporta {
            get {
                return this.indImportaField;
            }
            set {
                if ((this.indImportaField.Equals(value) != true)) {
                    this.indImportaField = value;
                    this.RaisePropertyChanged("indImporta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indImprime {
            get {
                return this.indImprimeField;
            }
            set {
                if ((this.indImprimeField.Equals(value) != true)) {
                    this.indImprimeField = value;
                    this.RaisePropertyChanged("indImprime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indMenu {
            get {
                return this.indMenuField;
            }
            set {
                if ((this.indMenuField.Equals(value) != true)) {
                    this.indMenuField = value;
                    this.RaisePropertyChanged("indMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indNuevo {
            get {
                return this.indNuevoField;
            }
            set {
                if ((this.indNuevoField.Equals(value) != true)) {
                    this.indNuevoField = value;
                    this.RaisePropertyChanged("indNuevo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indOtro {
            get {
                return this.indOtroField;
            }
            set {
                if ((this.indOtroField.Equals(value) != true)) {
                    this.indOtroField = value;
                    this.RaisePropertyChanged("indOtro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indVer {
            get {
                return this.indVerField;
            }
            set {
                if ((this.indVerField.Equals(value) != true)) {
                    this.indVerField = value;
                    this.RaisePropertyChanged("indVer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime segFechaHoraCrea {
            get {
                return this.segFechaHoraCreaField;
            }
            set {
                if ((this.segFechaHoraCreaField.Equals(value) != true)) {
                    this.segFechaHoraCreaField = value;
                    this.RaisePropertyChanged("segFechaHoraCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> segFechaHoraEdita {
            get {
                return this.segFechaHoraEditaField;
            }
            set {
                if ((this.segFechaHoraEditaField.Equals(value) != true)) {
                    this.segFechaHoraEditaField = value;
                    this.RaisePropertyChanged("segFechaHoraEdita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segMaquinaOrigen {
            get {
                return this.segMaquinaOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.segMaquinaOrigenField, value) != true)) {
                    this.segMaquinaOrigenField = value;
                    this.RaisePropertyChanged("segMaquinaOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segUsuarioCrea {
            get {
                return this.segUsuarioCreaField;
            }
            set {
                if ((object.ReferenceEquals(this.segUsuarioCreaField, value) != true)) {
                    this.segUsuarioCreaField = value;
                    this.RaisePropertyChanged("segUsuarioCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segUsuarioEdita {
            get {
                return this.segUsuarioEditaField;
            }
            set {
                if ((object.ReferenceEquals(this.segUsuarioEditaField, value) != true)) {
                    this.segUsuarioEditaField = value;
                    this.RaisePropertyChanged("segUsuarioEdita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioIngreso", Namespace="http://schemas.datacontract.org/2004/07/CROM.Seguridad.BussinesEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CROM.GC.Controllers.wcfSeguridad.UsuarioIngresoAux))]
    public partial class UsuarioIngreso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecAccesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime segFechaHoraEditaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segMaquinaOrigenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codRol {
            get {
                return this.codRolField;
            }
            set {
                if ((object.ReferenceEquals(this.codRolField, value) != true)) {
                    this.codRolField = value;
                    this.RaisePropertyChanged("codRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codSistema {
            get {
                return this.codSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.codSistemaField, value) != true)) {
                    this.codSistemaField = value;
                    this.RaisePropertyChanged("codSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codUsuario {
            get {
                return this.codUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.codUsuarioField, value) != true)) {
                    this.codUsuarioField = value;
                    this.RaisePropertyChanged("codUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desIngreso {
            get {
                return this.desIngresoField;
            }
            set {
                if ((object.ReferenceEquals(this.desIngresoField, value) != true)) {
                    this.desIngresoField = value;
                    this.RaisePropertyChanged("desIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desLogin {
            get {
                return this.desLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.desLoginField, value) != true)) {
                    this.desLoginField = value;
                    this.RaisePropertyChanged("desLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecAcceso {
            get {
                return this.fecAccesoField;
            }
            set {
                if ((this.fecAccesoField.Equals(value) != true)) {
                    this.fecAccesoField = value;
                    this.RaisePropertyChanged("fecAcceso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime segFechaHoraEdita {
            get {
                return this.segFechaHoraEditaField;
            }
            set {
                if ((this.segFechaHoraEditaField.Equals(value) != true)) {
                    this.segFechaHoraEditaField = value;
                    this.RaisePropertyChanged("segFechaHoraEdita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segMaquinaOrigen {
            get {
                return this.segMaquinaOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.segMaquinaOrigenField, value) != true)) {
                    this.segMaquinaOrigenField = value;
                    this.RaisePropertyChanged("segMaquinaOrigen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sistema", Namespace="http://schemas.datacontract.org/2004/07/CROM.Seguridad.BussinesEntities")]
    [System.SerializableAttribute()]
    public partial class Sistema : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime segFechaHoraCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> segFechaHoraEditaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segMaquinaOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segUsuarioCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segUsuarioEditaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codSistema {
            get {
                return this.codSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.codSistemaField, value) != true)) {
                    this.codSistemaField = value;
                    this.RaisePropertyChanged("codSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desDescripcion {
            get {
                return this.desDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.desDescripcionField, value) != true)) {
                    this.desDescripcionField = value;
                    this.RaisePropertyChanged("desDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desNombre {
            get {
                return this.desNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.desNombreField, value) != true)) {
                    this.desNombreField = value;
                    this.RaisePropertyChanged("desNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indEstado {
            get {
                return this.indEstadoField;
            }
            set {
                if ((this.indEstadoField.Equals(value) != true)) {
                    this.indEstadoField = value;
                    this.RaisePropertyChanged("indEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime segFechaHoraCrea {
            get {
                return this.segFechaHoraCreaField;
            }
            set {
                if ((this.segFechaHoraCreaField.Equals(value) != true)) {
                    this.segFechaHoraCreaField = value;
                    this.RaisePropertyChanged("segFechaHoraCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> segFechaHoraEdita {
            get {
                return this.segFechaHoraEditaField;
            }
            set {
                if ((this.segFechaHoraEditaField.Equals(value) != true)) {
                    this.segFechaHoraEditaField = value;
                    this.RaisePropertyChanged("segFechaHoraEdita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segMaquinaOrigen {
            get {
                return this.segMaquinaOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.segMaquinaOrigenField, value) != true)) {
                    this.segMaquinaOrigenField = value;
                    this.RaisePropertyChanged("segMaquinaOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segUsuarioCrea {
            get {
                return this.segUsuarioCreaField;
            }
            set {
                if ((object.ReferenceEquals(this.segUsuarioCreaField, value) != true)) {
                    this.segUsuarioCreaField = value;
                    this.RaisePropertyChanged("segUsuarioCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segUsuarioEdita {
            get {
                return this.segUsuarioEditaField;
            }
            set {
                if ((object.ReferenceEquals(this.segUsuarioEditaField, value) != true)) {
                    this.segUsuarioEditaField = value;
                    this.RaisePropertyChanged("segUsuarioEdita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolAux", Namespace="http://schemas.datacontract.org/2004/07/CROM.Seguridad.BussinesEntities")]
    [System.SerializableAttribute()]
    public partial class RolAux : CROM.GC.Controllers.wcfSeguridad.Rol {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codSistemaNombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codSistemaNombre {
            get {
                return this.codSistemaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.codSistemaNombreField, value) != true)) {
                    this.codSistemaNombreField = value;
                    this.RaisePropertyChanged("codSistemaNombre");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/CROM.Seguridad.BussinesEntities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CROM.GC.Controllers.wcfSeguridad.RolAux))]
    public partial class Rol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SegFechaHoraEditaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool indEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime segFechaHoraCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segMaquinaOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segUsuarioCreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segUsuarioEditaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SegFechaHoraEdita {
            get {
                return this.SegFechaHoraEditaField;
            }
            set {
                if ((this.SegFechaHoraEditaField.Equals(value) != true)) {
                    this.SegFechaHoraEditaField = value;
                    this.RaisePropertyChanged("SegFechaHoraEdita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codRol {
            get {
                return this.codRolField;
            }
            set {
                if ((object.ReferenceEquals(this.codRolField, value) != true)) {
                    this.codRolField = value;
                    this.RaisePropertyChanged("codRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codSistema {
            get {
                return this.codSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.codSistemaField, value) != true)) {
                    this.codSistemaField = value;
                    this.RaisePropertyChanged("codSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desDescripcion {
            get {
                return this.desDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.desDescripcionField, value) != true)) {
                    this.desDescripcionField = value;
                    this.RaisePropertyChanged("desDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desNombre {
            get {
                return this.desNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.desNombreField, value) != true)) {
                    this.desNombreField = value;
                    this.RaisePropertyChanged("desNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool indEstado {
            get {
                return this.indEstadoField;
            }
            set {
                if ((this.indEstadoField.Equals(value) != true)) {
                    this.indEstadoField = value;
                    this.RaisePropertyChanged("indEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime segFechaHoraCrea {
            get {
                return this.segFechaHoraCreaField;
            }
            set {
                if ((this.segFechaHoraCreaField.Equals(value) != true)) {
                    this.segFechaHoraCreaField = value;
                    this.RaisePropertyChanged("segFechaHoraCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segMaquinaOrigen {
            get {
                return this.segMaquinaOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.segMaquinaOrigenField, value) != true)) {
                    this.segMaquinaOrigenField = value;
                    this.RaisePropertyChanged("segMaquinaOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segUsuarioCrea {
            get {
                return this.segUsuarioCreaField;
            }
            set {
                if ((object.ReferenceEquals(this.segUsuarioCreaField, value) != true)) {
                    this.segUsuarioCreaField = value;
                    this.RaisePropertyChanged("segUsuarioCrea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segUsuarioEdita {
            get {
                return this.segUsuarioEditaField;
            }
            set {
                if ((object.ReferenceEquals(this.segUsuarioEditaField, value) != true)) {
                    this.segUsuarioEditaField = value;
                    this.RaisePropertyChanged("segUsuarioEdita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfSeguridad.IAccess")]
    public interface IAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/UserRolOptions", ReplyAction="http://tempuri.org/IAccess/UserRolOptionsResponse")]
        CROM.GC.Controllers.wcfSeguridad.UsuarioAux UserRolOptions(string prm_LoginUsuario, string prm_CodigoRol, string prm_CodigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/UserRolOptions", ReplyAction="http://tempuri.org/IAccess/UserRolOptionsResponse")]
        System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.UsuarioAux> UserRolOptionsAsync(string prm_LoginUsuario, string prm_CodigoRol, string prm_CodigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/ListUsuario", ReplyAction="http://tempuri.org/IAccess/ListUsuarioResponse")]
        CROM.GC.Controllers.wcfSeguridad.UsuarioAux[] ListUsuario(bool prmEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/ListUsuario", ReplyAction="http://tempuri.org/IAccess/ListUsuarioResponse")]
        System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.UsuarioAux[]> ListUsuarioAsync(bool prmEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/FindSistema", ReplyAction="http://tempuri.org/IAccess/FindSistemaResponse")]
        CROM.GC.Controllers.wcfSeguridad.Sistema FindSistema(string prm_CodigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/FindSistema", ReplyAction="http://tempuri.org/IAccess/FindSistemaResponse")]
        System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.Sistema> FindSistemaAsync(string prm_CodigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/ListRolUsuario", ReplyAction="http://tempuri.org/IAccess/ListRolUsuarioResponse")]
        CROM.GC.Controllers.wcfSeguridad.RolAux[] ListRolUsuario(string prm_LoginUsuario, string prm_CodigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/ListRolUsuario", ReplyAction="http://tempuri.org/IAccess/ListRolUsuarioResponse")]
        System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.RolAux[]> ListRolUsuarioAsync(string prm_LoginUsuario, string prm_CodigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/ListRol", ReplyAction="http://tempuri.org/IAccess/ListRolResponse")]
        CROM.GC.Controllers.wcfSeguridad.RolAux[] ListRol(string prm_CodigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/ListRol", ReplyAction="http://tempuri.org/IAccess/ListRolResponse")]
        System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.RolAux[]> ListRolAsync(string prm_CodigoSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/DetectLoginPassword", ReplyAction="http://tempuri.org/IAccess/DetectLoginPasswordResponse")]
        bool DetectLoginPassword(string prm_LoginUsuario, string prm_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/DetectLoginPassword", ReplyAction="http://tempuri.org/IAccess/DetectLoginPasswordResponse")]
        System.Threading.Tasks.Task<bool> DetectLoginPasswordAsync(string prm_LoginUsuario, string prm_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/DetectLoginPasswordExterno", ReplyAction="http://tempuri.org/IAccess/DetectLoginPasswordExternoResponse")]
        bool DetectLoginPasswordExterno(string prm_LoginUsuario, string prm_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/DetectLoginPasswordExterno", ReplyAction="http://tempuri.org/IAccess/DetectLoginPasswordExternoResponse")]
        System.Threading.Tasks.Task<bool> DetectLoginPasswordExternoAsync(string prm_LoginUsuario, string prm_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/UpdatePassword", ReplyAction="http://tempuri.org/IAccess/UpdatePasswordResponse")]
        bool UpdatePassword(string prm_LoginUsuario, string prm_NuevoPassword, bool prm_Externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/UpdatePassword", ReplyAction="http://tempuri.org/IAccess/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<bool> UpdatePasswordAsync(string prm_LoginUsuario, string prm_NuevoPassword, bool prm_Externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/UpdatePasswordRec", ReplyAction="http://tempuri.org/IAccess/UpdatePasswordRecResponse")]
        bool UpdatePasswordRec(string prm_LoginUsuario, string prm_NuevoPassword, string prm_SegMaquinaOrigen, string prm_SegUsuarioEdita, bool prm_Mail, bool prm_Externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/UpdatePasswordRec", ReplyAction="http://tempuri.org/IAccess/UpdatePasswordRecResponse")]
        System.Threading.Tasks.Task<bool> UpdatePasswordRecAsync(string prm_LoginUsuario, string prm_NuevoPassword, string prm_SegMaquinaOrigen, string prm_SegUsuarioEdita, bool prm_Mail, bool prm_Externo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/ListUsuarioIngreso", ReplyAction="http://tempuri.org/IAccess/ListUsuarioIngresoResponse")]
        CROM.GC.Controllers.wcfSeguridad.UsuarioIngresoAux[] ListUsuarioIngreso(string p_codUsuario, string p_codSistema, string p_codRol, System.Nullable<System.DateTime> p_fecInicio, System.Nullable<System.DateTime> p_fecFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/ListUsuarioIngreso", ReplyAction="http://tempuri.org/IAccess/ListUsuarioIngresoResponse")]
        System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.UsuarioIngresoAux[]> ListUsuarioIngresoAsync(string p_codUsuario, string p_codSistema, string p_codRol, System.Nullable<System.DateTime> p_fecInicio, System.Nullable<System.DateTime> p_fecFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/InsertUsuarioIngreso", ReplyAction="http://tempuri.org/IAccess/InsertUsuarioIngresoResponse")]
        bool InsertUsuarioIngreso(CROM.GC.Controllers.wcfSeguridad.UsuarioIngreso p_UsuarioIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccess/InsertUsuarioIngreso", ReplyAction="http://tempuri.org/IAccess/InsertUsuarioIngresoResponse")]
        System.Threading.Tasks.Task<bool> InsertUsuarioIngresoAsync(CROM.GC.Controllers.wcfSeguridad.UsuarioIngreso p_UsuarioIngreso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessChannel : CROM.GC.Controllers.wcfSeguridad.IAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessClient : System.ServiceModel.ClientBase<CROM.GC.Controllers.wcfSeguridad.IAccess>, CROM.GC.Controllers.wcfSeguridad.IAccess {
        
        public AccessClient() {
        }
        
        public AccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CROM.GC.Controllers.wcfSeguridad.UsuarioAux UserRolOptions(string prm_LoginUsuario, string prm_CodigoRol, string prm_CodigoSistema) {
            return base.Channel.UserRolOptions(prm_LoginUsuario, prm_CodigoRol, prm_CodigoSistema);
        }
        
        public System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.UsuarioAux> UserRolOptionsAsync(string prm_LoginUsuario, string prm_CodigoRol, string prm_CodigoSistema) {
            return base.Channel.UserRolOptionsAsync(prm_LoginUsuario, prm_CodigoRol, prm_CodigoSistema);
        }
        
        public CROM.GC.Controllers.wcfSeguridad.UsuarioAux[] ListUsuario(bool prmEstado) {
            return base.Channel.ListUsuario(prmEstado);
        }
        
        public System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.UsuarioAux[]> ListUsuarioAsync(bool prmEstado) {
            return base.Channel.ListUsuarioAsync(prmEstado);
        }
        
        public CROM.GC.Controllers.wcfSeguridad.Sistema FindSistema(string prm_CodigoSistema) {
            return base.Channel.FindSistema(prm_CodigoSistema);
        }
        
        public System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.Sistema> FindSistemaAsync(string prm_CodigoSistema) {
            return base.Channel.FindSistemaAsync(prm_CodigoSistema);
        }
        
        public CROM.GC.Controllers.wcfSeguridad.RolAux[] ListRolUsuario(string prm_LoginUsuario, string prm_CodigoSistema) {
            return base.Channel.ListRolUsuario(prm_LoginUsuario, prm_CodigoSistema);
        }
        
        public System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.RolAux[]> ListRolUsuarioAsync(string prm_LoginUsuario, string prm_CodigoSistema) {
            return base.Channel.ListRolUsuarioAsync(prm_LoginUsuario, prm_CodigoSistema);
        }
        
        public CROM.GC.Controllers.wcfSeguridad.RolAux[] ListRol(string prm_CodigoSistema) {
            return base.Channel.ListRol(prm_CodigoSistema);
        }
        
        public System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.RolAux[]> ListRolAsync(string prm_CodigoSistema) {
            return base.Channel.ListRolAsync(prm_CodigoSistema);
        }
        
        public bool DetectLoginPassword(string prm_LoginUsuario, string prm_Password) {
            return base.Channel.DetectLoginPassword(prm_LoginUsuario, prm_Password);
        }
        
        public System.Threading.Tasks.Task<bool> DetectLoginPasswordAsync(string prm_LoginUsuario, string prm_Password) {
            return base.Channel.DetectLoginPasswordAsync(prm_LoginUsuario, prm_Password);
        }
        
        public bool DetectLoginPasswordExterno(string prm_LoginUsuario, string prm_Password) {
            return base.Channel.DetectLoginPasswordExterno(prm_LoginUsuario, prm_Password);
        }
        
        public System.Threading.Tasks.Task<bool> DetectLoginPasswordExternoAsync(string prm_LoginUsuario, string prm_Password) {
            return base.Channel.DetectLoginPasswordExternoAsync(prm_LoginUsuario, prm_Password);
        }
        
        public bool UpdatePassword(string prm_LoginUsuario, string prm_NuevoPassword, bool prm_Externo) {
            return base.Channel.UpdatePassword(prm_LoginUsuario, prm_NuevoPassword, prm_Externo);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePasswordAsync(string prm_LoginUsuario, string prm_NuevoPassword, bool prm_Externo) {
            return base.Channel.UpdatePasswordAsync(prm_LoginUsuario, prm_NuevoPassword, prm_Externo);
        }
        
        public bool UpdatePasswordRec(string prm_LoginUsuario, string prm_NuevoPassword, string prm_SegMaquinaOrigen, string prm_SegUsuarioEdita, bool prm_Mail, bool prm_Externo) {
            return base.Channel.UpdatePasswordRec(prm_LoginUsuario, prm_NuevoPassword, prm_SegMaquinaOrigen, prm_SegUsuarioEdita, prm_Mail, prm_Externo);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePasswordRecAsync(string prm_LoginUsuario, string prm_NuevoPassword, string prm_SegMaquinaOrigen, string prm_SegUsuarioEdita, bool prm_Mail, bool prm_Externo) {
            return base.Channel.UpdatePasswordRecAsync(prm_LoginUsuario, prm_NuevoPassword, prm_SegMaquinaOrigen, prm_SegUsuarioEdita, prm_Mail, prm_Externo);
        }
        
        public CROM.GC.Controllers.wcfSeguridad.UsuarioIngresoAux[] ListUsuarioIngreso(string p_codUsuario, string p_codSistema, string p_codRol, System.Nullable<System.DateTime> p_fecInicio, System.Nullable<System.DateTime> p_fecFinal) {
            return base.Channel.ListUsuarioIngreso(p_codUsuario, p_codSistema, p_codRol, p_fecInicio, p_fecFinal);
        }
        
        public System.Threading.Tasks.Task<CROM.GC.Controllers.wcfSeguridad.UsuarioIngresoAux[]> ListUsuarioIngresoAsync(string p_codUsuario, string p_codSistema, string p_codRol, System.Nullable<System.DateTime> p_fecInicio, System.Nullable<System.DateTime> p_fecFinal) {
            return base.Channel.ListUsuarioIngresoAsync(p_codUsuario, p_codSistema, p_codRol, p_fecInicio, p_fecFinal);
        }
        
        public bool InsertUsuarioIngreso(CROM.GC.Controllers.wcfSeguridad.UsuarioIngreso p_UsuarioIngreso) {
            return base.Channel.InsertUsuarioIngreso(p_UsuarioIngreso);
        }
        
        public System.Threading.Tasks.Task<bool> InsertUsuarioIngresoAsync(CROM.GC.Controllers.wcfSeguridad.UsuarioIngreso p_UsuarioIngreso) {
            return base.Channel.InsertUsuarioIngresoAsync(p_UsuarioIngreso);
        }
    }
}
